name: CI/CD - Docker Build & Push

on:
  push:
    branches:
      - main  # O la rama que estés utilizando
  pull_request:
    branches:
      - main  # O la rama que estés utilizando

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build and Push Client Docker Image
    - name: Build and Push Client Docker image
      run: |
        docker build -f client/Dockerfile -t janneth5/cliente:latest --build-arg VITE_BACKEND_URL=${{ secrets.VITE_BACKEND_URL }} .
        docker push janneth5/cliente:latest

    # Build and Push Server Docker Image
    - name: Build and Push Server Docker image
      run: |
        docker build -f server/Dockerfile -t janneth5/servidor:latest \
          --build-arg JWT_SECRET=${{ secrets.JWT_SECRET }} \
          --build-arg SMTP_USER=${{ secrets.SMTP_USER }} \
          --build-arg SMTP_PASS=${{ secrets.SMTP_PASS }} \
          --build-arg SENDER_EMAIL=${{ secrets.SENDER_EMAIL }} .
        docker push janneth5/servidor:latest
